services:
  fe:
    container_name: fe
    image: node:18
    networks:
      - sentinel
    build:
      context: ./FE
      dockerfile: fe.dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - flask_mqtt
  flask_mqtt:
    container_name: flask_mqtt
    image: flask:1.0.0
    networks:
      - sentinel
    build:
      context: ./BE
      dockerfile: flask.dockerfile
    expose:
      - 4000
      - 1883
    ports:
      - 4000:4000
      - 1883:1883
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    networks:
      - sentinel
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
    sentinel:
        driver: bridge

volumes:
  pgdata: {}